include:
  - docker/cf-compose.yml
services:
  recc:
    build: .
    depends_on:
      cf:
        condition: service_healthy
        restart: true
    healthcheck:
      test: netstat | grep cf
      interval: 10s
      timeout: 30s
      retries: 3
    environment:
      RECCEIVER_RECCEIVER_PROCS: cf
      RECCEIVER_RECCEIVER_LOGLEVEL: DEBUG
      RECCEIVER_CF_INFOTAGS: archive
      RECCEIVER_CF_ALIAS: TRUE
      RECCEIVER_CF_RECORDTYPE: TRUE
      RECCEIVER_CF_RECORDDESC: TRUE
      RECCEIVER_CF_CLEANONSTART: TRUE
      RECCEIVER_CF_USERNAME: admin
      RECCEIVER_CF_CFUSERNAME: admin
      RECCEIVER_CF_CFPASSWORD: password
      RECCEIVER_CF_BASEURL: http://cf:8080/ChannelFinder
      RECCEIVER_CF_VERIFYSSL: FALSE
    volumes:
      - type: bind
        source: docker/config/cf.conf
        target: /home/recceiver/channelfinderapi.conf
        read_only: true
    networks:
      - net-1-recc-1
      - net-2-cf

networks:
  net-1-recc-1:
    driver: bridge
